### PR TITLE
Add aerosol from residual

### PR DESCRIPTION
**Pull request by maritsandstad**
<Please replace this paragraph by a description of what this PR does and alter the TODO-list below to what applies here. Please make a 'draft PR' to begin and then only mark it as ready for review once all the relevant points are done.>

- [x] Tests added
- [x] Documentation added
- [x] Example added (in the documentation, to an existing notebook, or in a new notebook)

### CODE REVIEW

**Comment by maritsandstad** [comment]
This might be ready now, only apprehension might be that prpatt still has some duplication of functionality, because the implementation of the residual anomaly functionality was based on slightly different takes on more or less the same thing...

**Comment by benmsanderson** [comment]
OK - initially got a bit confused before I appreciated how the 'anom' keywords were handled in the training data, but - what you've done is nice, and I think the way it's implemented is consistent with what we were doing in the notebooks before...  There's one minor issue I found, which maybe isn't causing trouble in the notebook example because we're only using the first 100 years of DACANOM to train the anomaly patterns.  But if you plot the full timeseries:

```
fld=prpatt.global_mean(canesm_anomsulf_pattern.dacanom['tas'])
plt.plot(1850+np.arange(len(fld)),fld)
plt.xlim(1850,2150)
```
there's a discontuities in 2000 and 2100 when the values reset to the initial state.  I haven't yet worked out why this is...


image

**Comment by benmsanderson** [comment]
Also, just to note it.  One of us - at some point - should also document how to label, train and use the anomaly functionality.

**Comment by maritsandstad** [comment]
> OK - initially got a bit confused before I appreciated how the 'anom' keywords were handled in the training data, but - what you've done is nice, and I think the way it's implemented is consistent with what we were doing in the notebooks before... There's one minor issue I found, which maybe isn't causing trouble in the notebook example because we're only using the first 100 years of DACANOM to train the anomaly patterns. But if you plot the full timeseries:
> 
> ```
> fld=prpatt.global_mean(canesm_anomsulf_pattern.dacanom['tas'])
> plt.plot(1850+np.arange(len(fld)),fld)
> plt.xlim(1850,2150)
> ```
> 
> there's a discontuities in 2000 and 2100 when the values reset to the initial state. I haven't yet worked out why this is...
> 
> image

That does look like a bug that should be solved... I'll see what I can do, but I can't make any promises for this week...  Inside the scope of what you had in your previous notebook, it should be entirely consistent, but I haven't done extensive testing outside that. Also, yes, documentation should be improved. However, it's hopefully slightly better than what's in the README as the documentations strings should be something we can automatically convert to docs (although I'm not sure I've set that up yet). Hopefully the documentation strings are somewhat sensible, in which case how to do that should be somewhat readable from those...

**Comment by benmsanderson** [comment]
OK - not a bug, just a slightly overzealous global_mean function which averages over the experiment dimension:  

```
fld=prpatt.global_mean(canesm_anomsulf_pattern.dacanom['pr'].sel(expt='sulxanom')[:,:,:])
plt.plot(1850+np.arange(len(fld)),fld)
plt.xlim(1850,2150)
```

image

**Comment by benmsanderson** [comment]
Sorry about that, pretty basic mistake - happy to sign off on this now, everything behaving.

**Pull request merged**
